# Generated by Django 3.2.9 on 2022-09-28 13:39

from django.db import migrations, models
import django.db.models.deletion
import picture.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=picture.utils.upload_file)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='product.product')),
            ],
        ),
    ]
